#!/bin/bash
#Server parameters
server="10.0.0.1" #Change this to your server's IP address
username="jim"
portnumber="20" #Your SSH server's port number.


#Excluded files
#I added an example excludes file based on files I've had problems with in the past.
path_to_excludes="...../rsyncexcludes.txt" #Change this to the path to the excludes file

#source and destination
#Please note that due to the nature of rsync, these MUST be absolute paths. They also
#must match on the source and destination, so if you mirror /home/joey/SyncMe on one
#machine, you'll get /home/joey/SyncMe on the other.
source_path="/..../SyncMe" #Path to what you're syncing plus the folder name itself
dest_path="/..../" #Path to what you're syncing without the folder itself

#Tools
excludes="--exclude-from $path_to_excludes" #if you prefer to hard-code exludes, use this variable instead of the excludes file
#Sets the server and port information. If no arguments, used settings above. Otherwise takes first argument as server and second as port.
#Note that the second argument depends on the first, but not vice-versa.
if [ $# -gt 0 ]; then
	server=$1
	if [ $# -gt 1 ]; then
		portnumber=$2
	fi
fi

#From here down is the code to sync stuff itself. Most of the params should be above.
rsync -avucr --info=progress2 $excludes -e "$sshcommand" $username@$server:$source_path $dest_path
if [ $? == 0 ]; then
	echo -e "\e[1;32mPull complete. Beginning push...\e[m"
else
	echo -e "\033[1;31mFailed to fetch updates. Please diagnose and rerun the script.\033[m"
	exit;
fi
rsync -avucr -info=progress2 $excludes -e "$sshcommand" $source_path $username@$server:$dest_path
if [ $? == 0 ]; then
	echo -e "\e[1;32mPush complete. Script is successful.\e[m"
else
	echo -e "\e[1;31mPush failed. Please diagnose and rerun the script.\e[m"
	exit;
fi
